// ESLint flat config for nuvet-api (NestJS 11 + Prisma 6 + Jest 30).
//
// Decisions logged inline:
// - ESLint 9 flat config (consistent with nuvet-web and nuvet-mobile).
// - @typescript-eslint v8 (latest 8.x line, supports ESLint 9 + TS 5.x).
// - No react-hooks plugin (NestJS, not React Native / Next.js).
// - Scope: src/**/*.ts, test/**/*.ts, and root test/setup files. Generated dirs
//   (dist, .expo equivalent, coverage, types/dist) are explicitly ignored.
// - ADR-007 (2026-07-08): ESLint flat-config chosen over Biome to match the
//   existing convention in nuvet-web and nuvet-mobile.
//
// Strictness calibration (2026-07-08 close-out of Fase 2 OLA 1):
// - `no-undef` is OFF. TypeScript's compiler handles type-aware undefined checks
//   better than ESLint. Several files (`storage.service.ts`, etc.) reference
//   ambient @types namespaces (`Express.Request`, etc.) that ESLint cannot see.
// - `no-redeclare` is OFF. Prisma's recommended service pattern uses class/interface
//   declaration merging (`class PrismaService` + `interface PrismaService {}`),
//   which ESLint flags redundantly with TypeScript's own checker.
// - `@typescript-eslint/no-unsafe-declaration-merging` is WARN. Same reason.
// - `@typescript-eslint/no-explicit-any` is WARN. The codebase has legacy `any`
//   types outside the Fase 2 consent/ scope; tightening is tracked in
//   PROJECT_STATE.md "Tech debt" and is not blocking for this OLA.

import js from '@eslint/js';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import globals from 'globals';

export default [
    // 1. Global ignores — apply to every subsequent config block.
    {
        ignores: [
            'node_modules/**',
            'dist/**',
            'coverage/**',
            'types/dist/**',
            // Migration files generated by Prisma.
            'prisma/migrations/**',
            // Config and root-level setup files outside the lint scope.
            'webpack-lambda.config.js',
            'jest.config.cjs',
            'nest-cli.json',
            'scripts/**',
        ],
    },

    // 2. Base JS recommended rules (catches undefined-vars, etc.).
    // NOTE: we disable `no-undef` here because TypeScript handles it better;
    // ESLint cannot see TS-only ambient types like `Express.Request`.
    js.configs.recommended,

    // 3. TS rules for the source tree.
    {
        files: [
            'src/**/*.ts',
            'src/**/*.spec.ts',
        ],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: 'latest',
                sourceType: 'module',
            },
            globals: {
                ...globals.node,
                ...globals.es2024,
            },
        },
        plugins: {
            '@typescript-eslint': tsPlugin,
        },
        rules: {
            ...tsPlugin.configs.recommended.rules,

            // Hand-listed overrides (see header note).
            'no-undef': 'off',
            'no-redeclare': 'off',
            '@typescript-eslint/no-require-imports': 'off',
            '@typescript-eslint/no-unsafe-declaration-merging': 'warn',
            '@typescript-eslint/no-empty-object-type': 'warn',

            // Allow _-prefixed unused identifiers (common for placeholder hooks
            // and intentionally-injected test fixtures).
            '@typescript-eslint/no-unused-vars': [
                'warn',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],

            // Existing codebase still has `any` in legacy modules outside the
            // Fase 2 consent/ work. Warn instead of error so we can tighten
            // incrementally as modules are modernized. Tracked in PROJECT_STATE.md.
            '@typescript-eslint/no-explicit-any': 'warn',
        },
    },

    // 4. Tests get Jest globals and looser any / non-null rules.
    {
        files: ['src/**/*.spec.ts'],
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.jest,
            },
        },
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-non-null-assertion': 'off',
        },
    },
];
